---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcloud-dns-updater
  namespace: {{ $.Values.namespace}}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gcloud-dns-updater
          restartPolicy: OnFailure
          containers:
          - name: gcloud-dns-updater
            image: pluies/gcloud_dns_updater
            env:
            - name: DNS_ZONE
              value: {{ $.Values.zone }}
            - name: DNS_SUBDOMAIN
              value: {{ $.Values.subdomain }}
            - name: GCLOUD_ZONE_NAME
              value: {{ $.Values.gcloud.zone_name }}
            - name: GCLOUD_DOMAIN
              value: {{ $.Values.gcloud.domain }}
