---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: blog-cert
  namespace: {{ $.Values.namespace }}
spec:
  secretName: blog-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - blog.florentdelannoy.com
  - kube.florentdelannoy.com
  - antipodes.plui.es

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: blog-cert-prod
  namespace: {{ $.Values.namespace }}
spec:
  secretName: blog-cert-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - blog.florentdelannoy.com
  - kube.florentdelannoy.com
  - antipodes.plui.es

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge-mapping
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-service
---
apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
