---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ $.Values.namespace }}
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      server {
        listen 80;
        access_log /dev/stdout;
        resolver kube-dns.kube-system.svc.cluster.local;
        location / {
          return 200 "EHLO";
        }
      }
    }
