---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: {{ $.Values.namespace }}
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: hugo
        image: pluies/blog
        ports:
        - containerPort: 80
