---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: {{ $.Values.namespace }}
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: hugo
        image: pluies/blog
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 20m
            memory: 32Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: antipodes
  namespace: {{ $.Values.namespace }}
  labels:
    app: antipodes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: antipodes
  template:
    metadata:
      labels:
        app: antipodes
    spec:
      containers:
      - name: antipodes
        image: pluies/antipodes
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: GOOGLE_MAPS_API_KEY
          value: {{ $.Values.antipodes.google_maps_api_key }}
