---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blog.florentdelannoy.com
    secretName: blog-ingress-tls
  rules:
  - host: blog.florentdelannoy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # TODO: figure out why this doesn't work
    nginx.org/location-snippets: |
      return 200 'Hello from Kube! 🥳';
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kube.florentdelannoy.com
    secretName: kube-ingress-tls
  rules:
  - host: kube.florentdelannoy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antipodes
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - antipodes.plui.es
    secretName: antipodes-ingress-tls
  rules:
  - host: antipodes.plui.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: antipodes
            port:
              number: 80

