---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
  namespace: {{ $.Values.namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
  namespace: {{ $.Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
  namespace: {{ $.Values.namespace }}
subjects:
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: certbot
  apiGroup: rbac.authorization.k8s.io
